project2/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from user import views as UserViews

from home import views

urlpatterns = [
    path('', include('home.urls')),
    path('user/', include('user.urls')),
    path('content/', include('content.urls')),
    path('aboutus/', views.aboutus, name='aboutus'),
    path('references/', views.references, name='references'),
    path('contact/', views.contact, name='contact'),
    path('search/', views.search, name='search'),
    path('search_auto/', views.search_auto, name='search_auto'),
    path('home/', include('home.urls')),
    path('product/', include('product.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('category/<int:id>/<slug:slug>', views.category_products, name='category_products'),
    path('product/<int:id>/<slug:slug>', views.product_detail, name='product_detail'),
    path('menu/<int:id>', views.menu, name='menu'),
    path('content/<int:id>/<slug:slug>', views.contentdetail, name='contentdetail'),
    path('login/', UserViews.login_form, name='login_form'),
    path('logout/', UserViews.logout_func, name='logout_func'),
    path('signup/', UserViews.signup_form, name='signup_form'),
    path('faq/', views.faq, name='faq'),
]

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('update/', views.user_update, name='user_update'),
    path('password/', views.user_password, name='user_password'),
    path('contents/', views.contents, name='contents'),
    path('addcontent/', views.addcontent, name='addcontent'),
    path('contentedit/<int:id>', views.contentedit, name='contentedit'),
    path('contentdelete/<int:id>', views.contentdelete, name='contentdelete'),
    path('contentaddimage/<int:id>', views.contentaddimage, name='contentaddimage'),

]

home/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.forms import ModelForm, TextInput, Textarea, Select


class Setting(models.Model):
    STATUS = (
        ('TRUE', 'EVET'),
        ('FALSE', 'HAYIR'),
    )
    title = models.CharField(max_length=200)
    description = models.CharField(max_length=300)
    keywords = models.CharField(max_length=255)
    company = models.CharField(max_length=50)
    address = models.CharField(blank=True,max_length=200)
    phone= models.CharField(blank=True,max_length=15)
    fax = models.CharField(blank=True,max_length=15)
    email = models.CharField(blank=True, max_length=50)
    smtpserver = models.CharField(blank=True,max_length=200)
    smtpemail = models.CharField(blank=True,max_length=20)
    smtppassword = models.CharField(blank=True,max_length=5)
    smtpport = models.CharField(blank=True,max_length=200)
    icon = models.ImageField(blank=True, upload_to='images/')
    facebook = models.CharField(blank=True,max_length=50)
    instagram = models.CharField(blank=True,max_length=50)
    twitter = models.CharField(blank=True,max_length=50)
    aboutus = RichTextUploadingField(blank=True,)
    contact = RichTextUploadingField(blank=True,)
    references = RichTextUploadingField(blank=True,)
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.title


class ContactFormMessage(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Read', 'Read'),
        ('Closed', 'Closed'),
    )
    name = models.CharField(blank=True,max_length=20)
    email = models.CharField(blank=True, max_length=50)
    subject = models.CharField(blank=True,max_length=50)
    message = models.CharField(blank=True, max_length=250)
    status = models.CharField(max_length=10, choices=STATUS,default='New')
    ip = models.CharField(blank=True, max_length=20)
    note = models.CharField(blank=True, max_length=100)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.name

class ContactForm(ModelForm):
    class Meta:
        model = ContactFormMessage
        fields = ['name','email','subject','message']
        widgets = {
            'name':TextInput(attrs={'class':'form-control','placeholder':'Name & Surname'}),
            'subject': TextInput(attrs={'class': 'form-control', 'placeholder': 'Subject'}),
            'email': TextInput(attrs={'class': 'form-control', 'placeholder': 'Email Address'}),
            'message': Textarea(attrs={'class': 'form-control', 'placeholder': 'Your Message','rows':'8'}),
        }



class FAQ(models.Model):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    ordernumber = models.IntegerField()
    question = models.CharField(max_length=150)
    answer = models.TextField()
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.question

user/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.utils.safestring import mark_safe

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(blank=True, max_length=20)
    address = models.CharField(blank=True, max_length=150)
    city = models.CharField(blank=True, max_length=20)
    country = models.CharField(blank=True, max_length=50)
    image = models.ImageField(blank=True, upload_to='images/users/')

    def __str__(self):
        return self.user.username

    def user_name(self):
        return self.user.first_name + ' ' + self.user.last_name + ' [' + self.user.username + '] '

    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))

    image_tag.short_description = 'Image'

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from django.forms import TextInput, EmailInput, Select, FileInput

from user.models import UserProfile


class SignUpForm(UserCreationForm):
    username = forms.CharField(max_length=30,label= 'Username :')
    email = forms.EmailField(max_length=200,label= 'Email :')
    first_name = forms.CharField(max_length=100, help_text='First Name',label= 'First Name :')
    last_name = forms.CharField(max_length=100, help_text='Last Name',label= 'Last Name :')

    class Meta:
        model = User
        fields = ('username', 'email','first_name','last_name', 'password1', 'password2', )


class UserUpdateForm(UserChangeForm):
    class Meta:
        model = User
        fields = ( 'username','email','first_name','last_name')
        widgets = {
            'username'  : TextInput(attrs={'class': 'input','placeholder':'username'}),
            'email'     : EmailInput(attrs={'class': 'input','placeholder':'email'}),
            'first_name': TextInput(attrs={'class': 'input','placeholder':'first_name'}),
            'last_name' : TextInput(attrs={'class': 'input','placeholder':'last_name' }),
        }

CITY = [
    ('Istanbul', 'Istanbul'),
    ('Ankara', 'Ankara'),
    ('Izmir', 'Izmir'),
]

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('phone', 'address', 'city','country','image')
        widgets = {
            'phone'     : TextInput(attrs={'class': 'input','placeholder':'phone'}),
            'address'   : TextInput(attrs={'class': 'input','placeholder':'address'}),
            'city'      : Select(attrs={'class': 'input','placeholder':'city'},choices=CITY),
            'country'   : TextInput(attrs={'class': 'input','placeholder':'country' }),
            'image'     : FileInput(attrs={'class': 'input', 'placeholder': 'image', }),
        }

user/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from content.models import Menu, Content, ContentForm, ContentImageForm, CImages
from home.models import Setting
from product.models import Category
from user.forms import SignUpForm, UserUpdateForm, ProfileUpdateForm
from user.models import UserProfile

def index(request):
    category = Category.objects.all()
    menu = Menu.objects.all()
    setting = Setting.objects.get(pk=1)
    current_user = request.user  # Access User Session information
    profile = UserProfile.objects.get(user_id=current_user.id)
    context = {'category': category,
        'profile': profile,
        'setting': setting,
        'menu': menu
    }
    return render(request, 'user_profile.html', context)


def login_form(request):
    if request.method =='POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            current_user = request.user
            userprofile = UserProfile.objects.get(user_id=current_user.id)
            request.session['userimage'] = userprofile.image.url
            return HttpResponseRedirect('/')
        else:
            messages.warning(request, "Login Error !!!  Username or Password is incorrect")
            return HttpResponseRedirect('/login')


    category = Category.objects.all()
    context = {'category': category}
    return render(request,'login.html',context)


def signup_form(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save() #completed sign up
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            # Create data in profile table for user
            current_user = request.user
            data = UserProfile()
            data.user_id = current_user.id
            data.image = "images/users/user.png"
            data.save()
            messages.success(request, 'Your account has been created!')
            return HttpResponseRedirect('/')
        else:
            messages.warning(request,form.errors)
            return HttpResponseRedirect('/signup')


    form = SignUpForm()
    category = Category.objects.all()
    context = {'category': category,
               'form': form,
               }
    return render(request, 'signup.html', context)

def logout_func(request):
    logout(request)
    return HttpResponseRedirect('/')


def user_update(request):
    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=request.user) # request.user is user  data
        profile_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.userprofile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Your account has been updated!')
            return HttpResponseRedirect('/user')
    else:
        category = Category.objects.all()
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.userprofile) #"userprofile" model -> OneToOneField relatinon with user
        context = {
            'category': category,
            'user_form': user_form,
            'profile_form': profile_form
        }
        return render(request, 'user_update.html', context)

def user_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return HttpResponseRedirect('/user')
        else:
            messages.error(request, 'Please correct the error below.<br>'+ str(form.errors))
            return HttpResponseRedirect('/user/password')
    else:
        category = Category.objects.all()
        form = PasswordChangeForm(request.user)
        return render(request, 'user_password.html', {'form': form,'category': category
                       })


@login_required(login_url='/login')
def contents(request):
    category=Category.objects.all()
    setting = Setting.objects.get(pk=1)
    menu=Menu.objects.all()
    current_user=request.user
    contents=Content.objects.filter(user_id=current_user.id)
    context={
        'category':category,
        'menu':menu,
        'setting': setting,
        'contents':contents,
    }
    return  render(request,'user_content.html',context)

@login_required(login_url='/login')
def addcontent(request):
    if request.method=='POST':
        form=ContentForm(request.POST,request.FILES)
        if form.is_valid():
            current_user=request.user
            data=Content()
            data.user_id=current_user.id
            data.title=form.cleaned_data['title']
            data.description = form.cleaned_data['description']
            data.keywords = form.cleaned_data['keywords']
            data.image = form.cleaned_data['image']
            data.price = form.cleaned_data['price']
            data.year = form.cleaned_data['year']
            data.fuel = form.cleaned_data['fuel']
            data.motor_power = form.cleaned_data['motor_power']
            data.engine_capacity = form.cleaned_data['engine_capacity']
            data.case_type = form.cleaned_data['case_type']
            data.slug = form.cleaned_data['slug']
            data.status='False'
            data.save()
            messages.success(request,'Your content ınserted susccessfully')
            return HttpResponseRedirect('/user/contents')
        else:
            messages.success(request, 'Content Form Error:'+ str(form.errors))
            return HttpResponseRedirect('/user/addcontent')
    else:
        category = Category.objects.all()
        form=ContentForm()
        setting = Setting.objects.get(pk=1)
        menu = Menu.objects.all()
        context = {
            'category': category,
            'menu': menu,
            'setting': setting,
            'form': form}
        return render(request,'user_addcontent.html',context)

@login_required(login_url='/login')
def contentedit(request,id):
    content = Content.objects.get(id=id)
    if request.method == 'POST':
        form = ContentForm(request.POST, request.FILES, instance=content)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your Content Updated Successfuly.')
            return HttpResponseRedirect('/user/contents')
        else:
            messages.warning(request, 'Content Form Error:' +str(form.errors))
            return HttpResponseRedirect('/user/contentedit/' +str(id))
    else:
        category = Category.objects.all()
        setting = Setting.objects.get(pk=1)
        menu = Menu.objects.all()
        form = ContentForm(instance=content)
        context = {
            'category': category,
            'menu': menu,
            'setting': setting,
            'form': form}
        return render(request, 'user_addcontent.html', context)


@login_required(login_url='/login')
def contentdelete(request,id):
    current_user = request.user
    Content.objects.filter(id=id, user_id=current_user.id).delete()
    messages.success(request, 'Content deleted.')
    return HttpResponseRedirect('/user/contents')

def contentaddimage(request, id):
    if request.method == 'POST':
        lasturl = request.META.get('HTTP_REFERER')
        form = ContentImageForm(request.POST, request.FILES)
        if form.is_valid():
            data = CImages()
            data.title = form.cleaned_data['title']
            data.content_id = id
            data.image = form.cleaned_data['image']
            data.save()
            messages.success(request, 'Your image has been successfully uploaded.')
            return HttpResponseRedirect(lasturl)
        else:
            messages.warning(request, 'Form Error:' + str(form.errors))
            return HttpResponseRedirect(lasturl)
    else:
        content = Content.objects.get(id=id)
        images = CImages.objects.filter(content_id = id)
        form = ContentImageForm()
        context = {
            'content': content,
            'images': images,
            'form': form
        }
        return render(request,'content_gallery.html', context)

user/templates/content_gallery.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Content Gallery</title>
</head>
<body>
<h2>{{content.title}}</h2><hr>

{% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{message.tags}}" role="alert">
        {{message | safe}}
    </div>
    {% endfor %}
{% endif %}

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="hidden" name="content_id" id="id_content_id" value="{{content.id}}">
    <label for="id_title">Title:</label>
    <input type="text" name="title" class="input" placeholder="Title" maxlength="50" id="id_title">
    <label for="id_image">Image:</label>
    <input type="file" name="image" class="input" placeholder="Image" accept="image/*" id="id_image">
    <button class="primary-btn" type="submit">Upload Image</button>
</form>
<hr>
<h4>Uploaded Photos </h4>
{% for rs in images %}
<hr>
    <img src="{{rs.image.url}}" height="200">
    {% endfor %}
</body>
</html>

user/templates/login.html
{%  extends "homebase.html" %}

{% block title %} User Login {% endblock %}

{% block keywords %}{{setting.keywords}}{% endblock %}

{% block description %}{{setting.description}}{% endblock %}
{% block head %}<link rel='shorcut icon' type="image/x-icon" href="{{setting.icon.url}}"/>{% endblock %}

{% block content %}
    <div class="breadcrumbs">
				<ol class="breadcrumb">
				  <li><a href="#">Home</a></li>
				  <li class="active">User Login</li>
				</ol>
    </div><!--/breadcrums-->
    <div class="section">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-sm-offset-1">
					<div class="login-form"><!--login form-->
						<h2>Login to your account</h2>

                        {% if messages %}
                            {% for message in messages %}
                                <div class="alert alert-{{message.tags}}" role="alert">
                                    {{ message }}
                                </div>
                            {% endfor %}
                        {% endif %}


						<form action="" method="post">
                             {% csrf_token %}
							<input type="text" class="input" name="username" placeholder="Username" />
                            <input type="password" class="input" name="password" placeholder="Password" />
							<span>
								<input type="checkbox" class="checkbox">
								Keep me signed in
							</span>
							<button type="submit" class="btn btn-default">Login</button>
						</form>
					</div><!--/login form-->






				</div>
            </div>
        </div>
    </div>



{% endblock %}

user/templates/signup.html
{%  extends "homebase.html" %}

{% block title %} User Sign Up {% endblock %}

{% block keywords %}{{setting.keywords}}{% endblock %}

{% block description %}{{setting.description}}{% endblock %}
{% block head %}<link rel='shorcut icon' type="image/x-icon" href="{{setting.icon.url}}"/>{% endblock %}

{% block content %}
    <div class="breadcrumbs">
				<ol class="breadcrumb">
				  <li><a href="#">Home</a></li>
				  <li class="active">User Sign Up</li>
				</ol>
    </div><!--/breadcrums-->
    <div class="section">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-sm-offset-1">
					<div class="login-form"><!--login form-->
						<h2>New User Signup!</h2>

                        {% if messages %}
                            {% for message in messages %}
                                <div class="alert alert-{{message.tags}}" role="alert">
                                    {{ message }}
                                </div>
                            {% endfor %}
                        {% endif %}


						<form action="" method="post">
                             {% csrf_token %}
                                {% for field in form %}
                                    <p>
                                        {{ field.label_tag }}<br>
                                        {{ field }}
                                        {% if field.help_text %}
                                            <small style="color: grey">{{ field.help_text }}</small>
                                        {% endif %}
                                        {% for error in field.errors %}
                                            <p style="color: red">{{ error }}</p>
                                        {% endfor %}
                                    </p>
                                {% endfor %}
							<button type="submit" class="btn btn-default">Signup</button>
						</form>
					</div><!--/login form-->






				</div>
            </div>
        </div>
    </div>



{% endblock %}

user/templates/user_addcontent.html
{%  extends "homebase.html" %}

{% block title %}{{ user.first_name }}Add Content {% endblock %}

{% block keywords %}{{setting.keywords}}{% endblock %}

{% block description %}{{setting.description}}{% endblock %}
{% block head %}
    <link rel='shorcut icon' type="image/x-icon" href="{{setting.icon.url}}"/>
    {% load static %}
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>



{% endblock %}

{% block content %}
    <div class="breadcrumbs">
				<ol class="breadcrumb">
				  <li><a href="#">Home</a></li>
				  <li class="active">User Add Content</li>
				</ol>
    </div><!--/breadcrums-->
    <div class="section">
        <div class="container">
            <div class="row">
                <div class="col-sm-3">
					{% include "user_panel.html" %}
				</div>


                <div class="col-sm-9">
                    <div>
                        <div class="login-form">
                            <h4 class="title">Add Content</h4>
                        </div>
                    </div>
                    <div class="content section">
                        <form method="POST" enctype="multipart/form-data">
                            {%  csrf_token %}
                            <fieldset class="form-group">
                                {{ form.media }}
                                {{ form.as_p }}
                            </fieldset>
                            <div class="form-group">
                                    <button type="submit" class="button light-blue">Save</button>
                            </div>
                        </form>
                    </div>
				</div>
            </div>
        </div>
    </div>



{% endblock %}

user/templates/user_content.html
{%  extends "homebase.html" %}

{% block title %}{{ user.first_name }} Content {% endblock %}

{% block keywords %}{{setting.keywords}}{% endblock %}

{% block description %}{{setting.description}}{% endblock %}
{% block head %}<link rel='shorcut icon' type="image/x-icon" href="{{setting.icon.url}}"/>{% endblock %}

{% block content %}
    <div class="breadcrumbs">
				<ol class="breadcrumb">
				  <li><a href="#">Home</a></li>
				  <li class="active">User Content</li>
				</ol>
    </div><!--/breadcrums-->
    <div class="section">
        <div class="container">
            <div class="row">
                <div class="col-sm-3">
					{% include "user_panel.html" %}
				</div>


                <div class="col-sm-9">
                    <div>
                        <div class="login-form">
                            <h4 class="title">User Content List <a class="btn-primary" href="/user/addcontent">Add Content</a> </h4>
                        </div>
                    </div>
                    <table>
                            <tr>
                                <td>Image</td>
                                <td>Title</td>
                                <td>Listing Date</td>
                                <td>Gallery</td>
                                <td>Status</td>
                                <td>Detail</td>
                            </tr>
                            {% for rs in contents %}
                            <tr>
                                <td>
                                    <a href="/content/{{ rs.id }}/{{ rs.slug }}">
                                    <img src="{{rs.image.url}}" alt="" width="200"></a>
                                </td>
                                <td> {{rs.title}}</td>
                                <td>{{rs.create_at}}</td>
                                <td><a href="javascript:;" onclick="window.open('/user/contentaddimage/{{ rs.id }}','gallery','height=600,width=800,top=50,left=150')">Gallery</a> </td>
                                <td> {{rs.status}}</td>
                                <td><a href="/user/contentedit/{{rs.id}}">Edit</a><br>
                                <a href="/user/contentdelete/{{rs.id}}" onclick="return confirm('Are you sure you want to delete the content?')">Delete</a>
                                </td>
                            </tr>
                            {% endfor %}
                        </table>

				</div>
            </div>
        </div>
    </div>



{% endblock %}

user/templates/user_panel.html
<div class="billing-details">
    <div class="section-title">
        <h3 class="title">User Panel</h3>
    </div>
    <div class="aside">
    <ul class="list-links">
        <li><a href="/user" class="btn btn-default">User Profile</a></li>
        <li><a href="/logout" class="btn btn-default">Logout</a></li>
    </ul>
</div>
</div>

user/templates/user_password.html
{%  extends "homebase.html" %}

{% block title %}{{ user.first_name }} Change Password {% endblock %}

{% block keywords %}{{setting.keywords}}{% endblock %}

{% block description %}{{setting.description}}{% endblock %}
{% block head %}<link rel='shorcut icon' type="image/x-icon" href="{{setting.icon.url}}"/>{% endblock %}

{% block content %}
    <div class="breadcrumbs">
				<ol class="breadcrumb">
				  <li><a href="#">Home</a></li>
				  <li class="active">Change Password</li>
				</ol>
    </div><!--/breadcrums-->
    <div class="section">
        <div class="container">
            <div class="row">
                <div class="col-sm-3">
					{% include "user_panel.html" %}
				</div>


                <div class="col-sm-9">
                    <div>
                        <div class="login-form">
                            <h2>User Change Password</h2>
                        </div>
                    </div>
                  {% if messages %}
                        {% for message in messages %}
                            <div style="color: #d43f3a; font-size: medium">
                                {{ message|safe }}
                            </div>
                        {% endfor %}
                  {% endif %}
                  <form method="post">
                      {% csrf_token %}
                      {% for field in form %}
                          <p>
                                {{ field.label_tag }}<br>
                                {{ field }}
                                {% if field.help_text %}
                                    <small style="color: grey">{{ field.help_text }}</small>
                                {% endif %}
                                {% for error in field.errors %}
                                    <p style="color: red">{{ error }}</p>
                                {% endfor %}
                          </p>
                        {% endfor %}
                        <button class="btn btn-default" type="submit">Save changes</button>
                    </form>
				</div>
            </div>
        </div>
    </div>



{% endblock %}

user/templates/user_profile.html
{%  extends "homebase.html" %}

{% block title %}{{ user.first_name }} Profile {% endblock %}

{% block keywords %}{{setting.keywords}}{% endblock %}

{% block description %}{{setting.description}}{% endblock %}
{% block head %}<link rel='shorcut icon' type="image/x-icon" href="{{setting.icon.url}}"/>{% endblock %}

{% block content %}
    <div class="breadcrumbs">
				<ol class="breadcrumb">
				  <li><a href="#">Home</a></li>
				  <li class="active">User Profile</li>
				</ol>
    </div><!--/breadcrums-->
    <div class="section">
        <div class="container">
            <div class="row">
                <div class="col-sm-3">
					{% include "user_panel.html" %}
				</div>


                <div class="col-sm-9">
                    <div>
                        <div class="login-form">
                            <h2>User Profile Information</h2>
                        </div>
                    </div>
                    <table class="shopping-cart-table table">
                        <tr>
                            <th class="text-left">
                                <a href="/user/update" class="btn btn-default">Update Profile</a>
                                <a href="/user/password" class="btn btn-default">Change Password</a>
                            </th>
                            <td><img src="{{ profile.image.url }}" style="border-radius: 45px; height: 200px "></td>
                        </tr>
                        <tr>
                            <th class="text-left">Name Surname</th>
                            <td class="text-left">{{ user.first_name}} {{ user.last_name}} </td>
                        </tr>
                        <tr>
                            <th class="text-left">Email</th>
                            <td class="text-left">{{ profile.user.email}}</td>
                        </tr>
                        <tr>
                            <th class="text-left">Phone</th>
                            <td class="text-left">{{ profile.phone}}</td>
                        </tr>
                        <tr>
                            <th class="text-left">Addres</th>
                            <td class="text-left">{{ profile.address}}</td>
                        </tr>
                        <tr>
                            <th class="text-left">City</th>
                            <td class="text-left">{{ profile.city}}</td>
                        </tr>
                        <tr>
                            <th class="text-left">Country</th>
                            <td class="text-left">{{ profile.country}}</td>
                        </tr>
                    </table>
				</div>
            </div>
        </div>
    </div>



{% endblock %}